import type { TradeType } from "./types";

export const TRADE_TYPES: { value: TradeType; label: string }[] = [
  { value: "builder", label: "Builder" },
  { value: "electrician", label: "Electrician" },
  { value: "plumber", label: "Plumber" },
  { value: "drainlayer", label: "Drainlayer" },
  { value: "painter", label: "Painter" },
  { value: "roofer", label: "Roofer" },
  { value: "landscaper", label: "Landscaper" },
  { value: "concrete", label: "Concrete" },
  { value: "fencer", label: "Fencer" },
  { value: "tiler", label: "Tiler" },
  { value: "gasfitter", label: "Gasfitter" },
  { value: "plasterer", label: "Plasterer" },
  { value: "demolition", label: "Demolition" },
  { value: "earthworks", label: "Earthworks" },
  { value: "other", label: "Other Trade" },
];

export const NZ_REGIONS = [
  "Northland",
  "Auckland",
  "Waikato",
  "Bay of Plenty",
  "Gisborne",
  "Hawke's Bay",
  "Taranaki",
  "Manawatu-Whanganui",
  "Wellington",
  "Tasman",
  "Nelson",
  "Marlborough",
  "West Coast",
  "Canterbury",
  "Otago",
  "Southland",
];

export const SERVICES_BY_TRADE: Record<TradeType, string[]> = {
  builder: [
    "New Builds",
    "Renovations",
    "Extensions",
    "Decks & Fencing",
    "Project Management",
    "Light Commercial",
    "Bathroom Renovations",
    "Kitchen Renovations",
  ],
  electrician: [
    "Residential Wiring",
    "Commercial Electrical",
    "Rewiring",
    "Switchboard Upgrades",
    "LED Lighting",
    "Heat Pump Installation",
    "EV Charger Installation",
    "Safety Inspections",
  ],
  plumber: [
    "General Plumbing",
    "Hot Water Systems",
    "Bathroom Plumbing",
    "Kitchen Plumbing",
    "Gas Fitting",
    "Drain Unblocking",
    "Leak Detection",
    "Backflow Prevention",
  ],
  drainlayer: [
    "Stormwater Systems",
    "Sewer Connections",
    "Septic Tanks",
    "Drain Repairs",
    "CCTV Drain Inspection",
    "Soak Holes",
    "Retaining Walls",
    "Site Drainage",
  ],
  painter: [
    "Interior Painting",
    "Exterior Painting",
    "Wallpapering",
    "Roof Painting",
    "Spray Painting",
    "Texture Coatings",
    "Deck Staining",
    "Commercial Painting",
  ],
  roofer: [
    "Roof Repairs",
    "Re-Roofing",
    "New Roofs",
    "Metal Roofing",
    "Tile Roofing",
    "Spouting & Gutters",
    "Roof Painting",
    "Leak Repairs",
  ],
  landscaper: [
    "Garden Design",
    "Paving & Paths",
    "Retaining Walls",
    "Planting",
    "Irrigation Systems",
    "Lawn Installation",
    "Outdoor Living",
    "Fencing",
  ],
  concrete: [
    "Driveways",
    "Foundations",
    "Paths & Patios",
    "Exposed Aggregate",
    "Coloured Concrete",
    "Polished Concrete",
    "Concrete Cutting",
    "Commercial Concrete",
  ],
  fencer: [
    "Timber Fencing",
    "Pool Fencing",
    "Security Fencing",
    "Rural Fencing",
    "Retaining Walls",
    "Gates & Automation",
    "Aluminium Fencing",
    "Fence Repairs",
  ],
  tiler: [
    "Bathroom Tiling",
    "Kitchen Splashbacks",
    "Floor Tiling",
    "Outdoor Tiling",
    "Waterproofing",
    "Mosaic Tiling",
    "Natural Stone",
    "Tile Repairs",
  ],
  gasfitter: [
    "Gas Installations",
    "Gas Hob Installation",
    "Gas Hot Water",
    "Gas Fireplace",
    "LPG Systems",
    "Gas Safety Checks",
    "Commercial Gas",
    "Gas Leak Detection",
  ],
  plasterer: [
    "Interior Plastering",
    "Exterior Plastering",
    "Gib Stopping",
    "Texture Coatings",
    "Solid Plaster",
    "Plaster Repairs",
    "Ceilings",
    "Commercial Plastering",
  ],
  demolition: [
    "House Demolition",
    "Commercial Demolition",
    "Partial Demolition",
    "Asbestos Removal",
    "Site Clearing",
    "Salvage & Recycling",
    "Strip Outs",
    "Bobcat Work",
  ],
  earthworks: [
    "Site Preparation",
    "Excavation",
    "Retaining Walls",
    "Driveways",
    "Land Clearing",
    "Fill & Compaction",
    "Drainage",
    "Bobcat & Digger Hire",
  ],
  other: [
    "Residential Work",
    "Commercial Work",
    "Repairs & Maintenance",
    "New Installations",
    "Free Quotes",
    "Emergency Callouts",
  ],
};

export const TRADE_TESTIMONIALS: Record<TradeType, { name: string; text: string; location: string }[]> = {
  builder: [
    { name: "Sarah M.", text: "Built our dream home extension. Professional from start to finish.", location: "Auckland" },
    { name: "Dave K.", text: "Top quality renovation work. On time and on budget.", location: "Christchurch" },
    { name: "Lisa T.", text: "Couldn't be happier with our new deck. Highly recommend.", location: "Wellington" },
  ],
  electrician: [
    { name: "Mark P.", text: "Rewired our entire house. Clean, tidy work and great communication.", location: "Hamilton" },
    { name: "Jenny R.", text: "Fast response for an emergency callout. Fixed the issue in no time.", location: "Auckland" },
    { name: "Tom S.", text: "Installed our EV charger perfectly. Very knowledgeable.", location: "Tauranga" },
  ],
  plumber: [
    { name: "Anna W.", text: "Fixed a tricky leak that two other plumbers couldn't find.", location: "Wellington" },
    { name: "Chris B.", text: "Installed our new hot water system. Great advice on the best option.", location: "Auckland" },
    { name: "Rachel H.", text: "Always reliable and honest. Our go-to plumber for years.", location: "Dunedin" },
  ],
  drainlayer: [
    { name: "Steve L.", text: "Sorted our stormwater issues properly. No more flooding.", location: "Auckland" },
    { name: "Karen M.", text: "Professional job on our new sewer connection. Clean site.", location: "Hamilton" },
    { name: "Pete D.", text: "CCTV inspection found the exact problem. Saved us thousands.", location: "Christchurch" },
  ],
  painter: [
    { name: "Michelle G.", text: "Transformed our home inside and out. Stunning colour choices.", location: "Auckland" },
    { name: "Ian F.", text: "Professional spray job on our roof. Looks brand new.", location: "Wellington" },
    { name: "Sue K.", text: "Attention to detail is outstanding. Very tidy workers.", location: "Tauranga" },
  ],
  roofer: [
    { name: "Greg T.", text: "Fixed our leaking roof in one day. No more buckets!", location: "Auckland" },
    { name: "Diane M.", text: "Complete re-roof done efficiently. Great communication throughout.", location: "Christchurch" },
    { name: "Paul R.", text: "New spouting and gutters look fantastic. Fair price too.", location: "Hamilton" },
  ],
  landscaper: [
    { name: "Emma L.", text: "Designed and built our outdoor entertaining area. We love it.", location: "Auckland" },
    { name: "James C.", text: "Beautiful garden design. Really listened to what we wanted.", location: "Wellington" },
    { name: "Wendy S.", text: "Professional paving job. Transformed our backyard.", location: "Tauranga" },
  ],
  concrete: [
    { name: "Rob M.", text: "Exposed aggregate driveway looks amazing. Top quality work.", location: "Auckland" },
    { name: "Helen P.", text: "Polished concrete floors throughout. Absolutely love them.", location: "Christchurch" },
    { name: "Simon K.", text: "Foundation work was done perfectly. Very professional crew.", location: "Hamilton" },
  ],
  fencer: [
    { name: "Tony B.", text: "Beautiful timber fence. Looks fantastic and very solid.", location: "Auckland" },
    { name: "Marie D.", text: "Pool fencing done to code. Quick turnaround.", location: "Tauranga" },
    { name: "Bruce W.", text: "Automated gate works perfectly. Great service.", location: "Wellington" },
  ],
  tiler: [
    { name: "Leanne R.", text: "Bathroom tiling is flawless. Amazing attention to detail.", location: "Auckland" },
    { name: "Darren H.", text: "Kitchen splashback looks incredible. Very clean work.", location: "Christchurch" },
    { name: "Kathy N.", text: "Outdoor tiling around the pool. Looks like a resort.", location: "Hamilton" },
  ],
  gasfitter: [
    { name: "John M.", text: "Installed our gas hob and fireplace. Everything works perfectly.", location: "Wellington" },
    { name: "Alison T.", text: "Safety check gave us peace of mind. Very thorough.", location: "Auckland" },
    { name: "Wayne P.", text: "Fast and efficient LPG installation. Highly recommend.", location: "Christchurch" },
  ],
  plasterer: [
    { name: "Sandra L.", text: "Interior plastering is smooth as glass. Excellent finish.", location: "Auckland" },
    { name: "Mike C.", text: "Repaired our exterior plaster perfectly. Can't see the join.", location: "Wellington" },
    { name: "Fiona K.", text: "Gib stopping in our new build was flawless.", location: "Hamilton" },
  ],
  demolition: [
    { name: "Rick J.", text: "House demo done safely and on time. Very professional.", location: "Auckland" },
    { name: "Tina M.", text: "Strip out was clean and efficient. Site left tidy.", location: "Christchurch" },
    { name: "Grant S.", text: "Handled our asbestos removal properly. Peace of mind.", location: "Wellington" },
  ],
  earthworks: [
    { name: "Kevin B.", text: "Site prep done quickly. Ready for the builders on time.", location: "Auckland" },
    { name: "Dawn R.", text: "Driveway excavation was perfect. Very experienced operators.", location: "Hamilton" },
    { name: "Allan M.", text: "Drainage sorted our boggy section. Great result.", location: "Tauranga" },
  ],
  other: [
    { name: "Jo P.", text: "Professional service from start to finish. Highly recommend.", location: "Auckland" },
    { name: "Sam T.", text: "Quality workmanship and great communication.", location: "Wellington" },
    { name: "Liz K.", text: "Reliable, honest and did a fantastic job.", location: "Christchurch" },
  ],
};

export const TEMPLATE_PRESETS: Record<string, { designTokens: import("./types").ExtractedDesignTokens; label: string }> = {
  builder: {
    label: "Solid Ground",
    designTokens: {
      colors: { primary: "#2C3E50", secondary: "#E67E22", accent: "#F39C12", background: "#FAFAFA", text: "#2C3E50" },
      fonts: { heading: "Montserrat", body: "Open Sans" },
      style: "bold",
      layoutPatterns: ["hero-full", "services-grid", "testimonial-cards"],
    },
  },
  electrician: {
    label: "Bright Spark",
    designTokens: {
      colors: { primary: "#1A237E", secondary: "#FFC107", accent: "#FF9800", background: "#FFFFFF", text: "#212121" },
      fonts: { heading: "Poppins", body: "Inter" },
      style: "corporate",
      layoutPatterns: ["hero-split", "services-list", "cta-banner"],
    },
  },
  plumber: {
    label: "Clear Flow",
    designTokens: {
      colors: { primary: "#0277BD", secondary: "#00BCD4", accent: "#FF5722", background: "#F5F5F5", text: "#37474F" },
      fonts: { heading: "Raleway", body: "Roboto" },
      style: "minimal",
      layoutPatterns: ["hero-centered", "services-grid", "contact-split"],
    },
  },
  painter: {
    label: "True Level",
    designTokens: {
      colors: { primary: "#5D4037", secondary: "#8D6E63", accent: "#FF8F00", background: "#FFF8E1", text: "#3E2723" },
      fonts: { heading: "Playfair Display", body: "Lato" },
      style: "warm",
      layoutPatterns: ["hero-full", "portfolio-grid", "testimonial-slider"],
    },
  },
  roofer: {
    label: "Iron Edge",
    designTokens: {
      colors: { primary: "#263238", secondary: "#B71C1C", accent: "#FF5252", background: "#ECEFF1", text: "#263238" },
      fonts: { heading: "Oswald", body: "Source Sans Pro" },
      style: "dark",
      layoutPatterns: ["hero-full", "services-icons", "stats-bar"],
    },
  },
  landscaper: {
    label: "Green Acres",
    designTokens: {
      colors: { primary: "#2E7D32", secondary: "#795548", accent: "#8BC34A", background: "#F1F8E9", text: "#33691E" },
      fonts: { heading: "Merriweather", body: "Nunito" },
      style: "rustic",
      layoutPatterns: ["hero-split", "portfolio-masonry", "testimonial-cards"],
    },
  },
};
